# Generated by Django 5.2 on 2026-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='is_read',
            field=models.BooleanField(blank=True),
        ),
    ]
