# Generated by Django 5.2 on 2026-07-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_contactmodel_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
