# Generated by Django 5.2 on 2026-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmodel_updated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=200),
        ),
    ]
