# Generated by Django 5.2 on 2026-07-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
    ]
