# Generated by Django 5.2 on 2026-07-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitemmodel_product_variant_and_more'),
        ('shop', '0004_alter_categorymodel_slug_alter_productmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.productvariant'),
        ),
    ]
