# Generated by Django 5.2 on 2026-07-05 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitemmodel_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='product',
            new_name='product_variant',
        ),
    ]
