# Generated by Django 5.2 on 2026-07-08 19:21

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponmodel',
            name='expiered_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 8, 19, 21, 9, 419577, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='used_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
