# Generated by Django 5.2 on 2026-07-09 18:32

import accounts.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_couponmodel_expiered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='addressmodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[accounts.validators.validate_iranian_cellphone_number]),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiered_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 9, 18, 32, 2, 455795, tzinfo=datetime.timezone.utc)),
        ),
    ]
