# Generated by Django 5.2 on 2026-07-10 09:57

import accounts.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_addressmodel_fullname_addressmodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[accounts.validators.validate_iranian_cellphone_number]),
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiered_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 10, 9, 57, 35, 452773, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='AddressModel',
        ),
    ]
