# Generated by Django 5.2 on 2026-07-15 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderitemmodel_price_ordermodel_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='max_limit_user',
            new_name='max_limit_usage',
        ),
        migrations.AlterField(
            model_name='couponmodel',
            name='expiered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
